### ISSUE TITLE
JDK11+ compilation failure: package javax.xml.bind.annotation does not exist

### ISSUE THREAD

**Issue by minfrin** [highsource/jaxb-tools#190]
Upgrading a project from jdk8 to jdk11, we get the following compile errors:

```
[ERROR] /Users/minfrin/src/code/trunk/plist/target/generated-sources/xjc/fm/sharp/plist/Date.java:[11,33] package javax.xml.bind.annotation does not exist
[ERROR] /Users/minfrin/src/code/trunk/plist/target/generated-sources/xjc/fm/sharp/plist/Date.java:[12,33] package javax.xml.bind.annotation does not exist
[ERROR] /Users/minfrin/src/code/trunk/plist/target/generated-sources/xjc/fm/sharp/plist/Date.java:[13,33] package javax.xml.bind.annotation does not exist
```

The cause is the deprecation and removal of javax.xml.bind:

https://stackoverflow.com/questions/52502189/java-11-package-javax-xml-bind-does-not-exist

Using the recommended replacement jar as follows:

```
<dependency>
  <groupId>jakarta.xml.bind</groupId>
  <artifactId>jakarta.xml.bind-api</artifactId>
  <version>2.3.3</version>
</dependency>
```

the catalogs break as follows:

```
[ERROR] testRemoveKey(fm.sharp.plist.PlistUtilsTest)  Time elapsed: 0.046 s  <<< ERROR!
javax.xml.bind.UnmarshalException
	at fm.sharp.plist.PlistUtilsTest.setUp(PlistUtilsTest.java:27)
Caused by: org.xml.sax.SAXParseException: External DTD: Failed to read external DTD 'PropertyList-1.0.dtd', because 'http' access is not allowed due to restriction set by the accessExternalDTD property.
	at fm.sharp.plist.PlistUtilsTest.setUp(PlistUtilsTest.java:27)
```

It looks like jaxb2-plugin cannot generate working code past jdk8.

**Comment by weberhofer** [comment]
I think this is related to #148
It would be great if a new version 0.14.1 could be released!

**Comment by laurentschoelens** [comment]
@minfrin : could you confirm that with the latest releases, this issue is fixed ? Thanks

**Comment by laurentschoelens** [comment]
Closing as completed due to release of recent plugin based on updated xjc supporting jdk11 ...
