### ISSUE TITLE
after upgrade to JAXB 3, building ogc-schemas fails with AssertionError in javadoc 

### ISSUE THREAD

**Issue by soc** [highsource/jaxb-tools#434]
(Less of a bug report, more of an attempt to keep you informed and in the loop.)

My changes are [here](https://github.com/ogc-schemas/ogc-schemas/commits/master).

I tried building with Java 11 and Java 17.
I have already looked in the OpenJDK bug tracker, but haven't found an *exact* match so far.

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.5.0:jar (attach-javadocs) on project citygml-v_1_0: MavenReportException: Error while generating Javadoc: 
[ERROR] Exit code: 4
[ERROR] /home/soc/code/ogc-schemas/citygml/1.0/target/generated-sources/xjc/net/opengis/citygml/v_1_0/AbstractCityObjectType.java:121: error: cannot access CopyTo
[ERROR] public abstract class AbstractCityObjectType
[ERROR]                 ^
[ERROR]   class file for org.jvnet.jaxb.lang.CopyTo not found
[ERROR] /home/soc/code/ogc-schemas/citygml/1.0/target/generated-sources/xjc/net/opengis/citygml/cityfurniture/v_1_0/CityFurnitureType.java:100: error: cannot access Equals
[ERROR] public class CityFurnitureType
[ERROR]        ^
[ERROR]   class file for org.jvnet.jaxb.lang.Equals not found
[ERROR] /home/soc/code/ogc-schemas/citygml/1.0/target/generated-sources/xjc/net/opengis/citygml/v_1_0/ImplicitRepresentationPropertyType.java:59: error: cannot access MergeFrom
[ERROR] public class ImplicitRepresentationPropertyType
[ERROR]        ^
[ERROR]   class file for org.jvnet.jaxb.lang.MergeFrom not found
[ERROR] error: fatal error encountered: java.lang.AssertionError
[ERROR] error: Please file a bug against the javadoc tool via the Java bug reporting page
[ERROR]   (https://bugreport.java.com) after checking the Bug Database (https://bugs.java.com)
[ERROR]   for duplicates. Include error messages and the following diagnostic in your report. Thank you.
[ERROR] java.lang.AssertionError
[ERROR] 	at jdk.compiler/com.sun.tools.javac.util.Assert.error(Assert.java:155)
[ERROR] 	at jdk.compiler/com.sun.tools.javac.util.Assert.checkNonNull(Assert.java:62)
[ERROR] 	at jdk.compiler/com.sun.tools.javac.comp.Check.validateTypeAnnotation(Check.java:3088)
[ERROR] 	at jdk.compiler/com.sun.tools.javac.comp.Attr$TypeAnnotationsValidator.visitAnnotation(Attr.java:5587)
[ERROR] 	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCAnnotation.accept(JCTree.java:2908)
[ERROR] 	at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
[ERROR] 	at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:57)
[ERROR] 	at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.visitModifiers(TreeScanner.java:382)
[ERROR] 	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCModifiers.accept(JCTree.java:2937)
[ERROR] 	at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
[ERROR] 	at jdk.compiler/com.sun.tools.javac.comp.Attr$TypeAnnotationsValidator.visitClassDef(Attr.java:5670)
[ERROR] 	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:819)
[ERROR] 	at jdk.compiler/com.sun.tools.javac.comp.Attr.validateTypeAnnotations(Attr.java:5576)
[ERROR] 	at jdk.compiler/com.sun.tools.javac.code.TypeAnnotations.lambda$validateTypeAnnotationsSignatures$1(TypeAnnotations.java:135)
[ERROR] 	at jdk.compiler/com.sun.tools.javac.comp.Annotate.flush(Annotate.java:201)
[ERROR] 	at jdk.compiler/com.sun.tools.javac.comp.Annotate.unblockAnnotations(Annotate.java:145)
[ERROR] 	at jdk.compiler/com.sun.tools.javac.comp.Annotate.enterDone(Annotate.java:158)
[ERROR] 	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.enterDone(JavaCompiler.java:1723)
[ERROR] 	at jdk.javadoc/jdk.javadoc.internal.tool.JavadocEnter.main(JavadocEnter.java:78)
[ERROR] 	at jdk.javadoc/jdk.javadoc.internal.tool.JavadocTool.getEnvironment(JavadocTool.java:211)
[ERROR] 	at jdk.javadoc/jdk.javadoc.internal.tool.Start.parseAndExecute(Start.java:546)
[ERROR] 	at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:393)
[ERROR] 	at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:342)
[ERROR] 	at jdk.javadoc/jdk.javadoc.internal.tool.Main.execute(Main.java:63)
[ERROR] 	at jdk.javadoc/jdk.javadoc.internal.tool.Main.main(Main.java:52)
[ERROR] 5 errors
[ERROR] Command line was: /home/soc/.sdkman/candidates/java/17.0.7-tem/bin/javadoc @options @packages
[ERROR] 
[ERROR] Refer to the generated Javadoc files in '/home/soc/code/ogc-schemas/citygml/1.0/target/apidocs' dir.
```

**Comment by laurentschoelens** [comment]
Does your jar includes jaxb-plugins-runtime ?
The class your looking for is there

**Comment by soc** [comment]
The module (and all others) inherit from the Maven parent that contains `jaxb-plugins-runtime` as a dependency, otherwise nothing wouldn't compile in the first place; it's only the javadoc step that cannot find the classes.

**Comment by laurentschoelens** [comment]
@soc 
I'll try to build your project javadoc tomorrow.
Since you dropped jdk8 support, I'd suggest you to move to v4 of jaxb-tools
You should also upgrade your bindings namespace even if we tried to support older with newer def.

I'll keep you updated

**Comment by soc** [comment]
@laurentschoelens Thanks! I'm fine with going back to Java 8, but then I'll have to release new artifacts of w3c-schemas, too.

**Comment by laurentschoelens** [comment]
@soc Found the culprit 🎉 

You changed from JDK8 to JDK11 source here :
https://github.com/ogc-schemas/ogc-schemas/commit/340a16626e1fe54fa462a0bd620d6f565a296cee

And you're having maven-javadoc-plugin in 3.5.0 version (you upgraded not so long ago, before moving to JDK11 : https://github.com/ogc-schemas/ogc-schemas/commit/1696051b790e65721994f1ff55a6aef9b5804a81?diff=split)

The point is javadoc-plugin use module-based system if source is defined to be JDK9+
They fixed it by releasing 3.6.0 javadoc plugin with extra `legacyMode` tag : https://issues.apache.org/jira/browse/MJAVADOC-770

With the following diff, I've managed to build javadoc without any problem 😄 
<img width="792" alt="image" src="https://github.com/highsource/jaxb-tools/assets/61973605/04c37da3-f4da-4a0f-bbf9-85f8046c454b">

**Comment by soc** [comment]
The move from Java 8 to Java 11 was intentional, because I wanted to start replacing the automatic module names in the manifest with "real" module-info files in a future version.

> With the following diff, I've managed to build javadoc without any problem 😄

Thank you, I will try it at once! I assume that `legacyMode` is not a solution forever, but I'll take it if it means I can get ogc-schemas published.

**Comment by laurentschoelens** [comment]
This is what is said in javadoc maven plugin doc about `legacyMode`

```
Run the javadoc tool in pre-Java 9 (non-modular) style even if the java version is post java 9. This allows non-JPMS projects that have moved to newer Java versions to create javadocs without having to use JPMS modules.
Default value is: false.
User property is: legacyMode.
```
